/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasilaundry;

import static aplikasilaundry.Login.useraktif;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Mufidatun
 */
public class frmMain extends javax.swing.JFrame {

    /**
     * Creates new form frmMain
     */
    int hariawalint, beratint, totalharga,hari;
    
    public static String useraktif;
    public static String nama;
    public static String berat;
    public static String Tglmasuk;
    public static String jenis;
    public static String Tglselesai;
    public static String harga;
    public static String bulan;
    public static String tahun;
    public frmMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Jenis = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Admin = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        S = new javax.swing.JRadioButton();
        C = new javax.swing.JRadioButton();
        CK = new javax.swing.JRadioButton();
        CKS = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Tm = new javax.swing.JTextField();
        B = new javax.swing.JComboBox<>();
        T = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Laundry Kita");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(165, 17, 199, 29);

        jLabel2.setText("Admin :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(56, 64, 53, 14);
        jPanel1.add(Admin);
        Admin.setBounds(110, 60, 77, 20);

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 39, 14);
        jPanel1.add(Nama);
        Nama.setBounds(91, 96, 190, 30);

        jLabel4.setText("Berat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 40, 14);
        jPanel1.add(Berat);
        Berat.setBounds(90, 140, 140, 30);

        jLabel5.setText("gram");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 150, 37, 14);

        jLabel6.setText("Tanggal Masuk");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 190, 93, 14);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Jenis"));

        Jenis.add(S);
        S.setText("Selimut");

        Jenis.add(C);
        C.setText("Cuci");

        Jenis.add(CK);
        CK.setText("Cuci Kering");

        Jenis.add(CKS);
        CKS.setText("Cuci Kering Setrika");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(S)
                    .addComponent(C)
                    .addComponent(CK)
                    .addComponent(CKS))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(S)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(C)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CK)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CKS)
                .addGap(0, 7, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(299, 64, 174, 122);

        jButton1.setText("Lanjutkan");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(382, 221, 91, 23);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(299, 214, 77, 30);
        jPanel1.add(Tm);
        Tm.setBounds(120, 180, 30, 30);

        B.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(B);
        B.setBounds(160, 180, 40, 30);

        T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022" }));
        jPanel1.add(T);
        T.setBounds(210, 180, 70, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -4, 500, 260);

        setSize(new java.awt.Dimension(516, 291));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        String halouser = Login.useraktif;
        Admin.setText(halouser);
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                   
        String jeniscuci = "";
                if (S.isSelected()){
                    jeniscuci = "Selimut";}
                if (C.isSelected()){
                    jeniscuci = "Cuci"; }
                if (CK.isSelected()){
                    jeniscuci = "Cuci Kering";}
                if (CKS.isSelected()){
                    jeniscuci = "Cuci Kering Setrika";}
        
        if ("".equals(Nama.getText()) || "".equals(Berat.getText()) || "".equals(Tm.getText()) ||"".equals(B.getSelectedItem()) || "".equals(T.getSelectedItem())) {
            JOptionPane.showMessageDialog(this, "Harap Lengkapi Data", "Error", JOptionPane.WARNING_MESSAGE);
        } else {
            int hrg1 = 6;
            int hrg2 = 2;
            int hrg3 = 3;
            int hrg4 = 4;
            
            String hariawal = Tm.getText();
            
            String beratcuci = Berat.getText();
            
            hariawalint = Integer.parseInt(hariawal);
            hari = hariawalint + 2;
            String hari2 = Integer.toString(hari);
            beratint = Integer.parseInt(beratcuci);

            if( jeniscuci == "Selimut"){
                totalharga = beratint * hrg1; }
            if(jeniscuci == "Cuci"){
                totalharga = beratint * hrg2; }
            if(jeniscuci == "Cuci Kering"){
                totalharga = beratint * hrg3; }
            if( jeniscuci == "Cuci Kering Setrika"){
                totalharga = beratint * hrg4; }
                
            
            String hargafinal = Integer.toString(totalharga);
                        
            new frmMain2().show();
            nama = Nama.getText();
            berat = Berat.getText();
            Tglmasuk = hariawal;
            jenis = jeniscuci;
            Tglselesai = hari2;
            harga = hargafinal;  
            bulan = B.getSelectedItem().toString();
            tahun = T.getSelectedItem().toString();
          
            
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JComboBox<String> B;
    private javax.swing.JTextField Berat;
    private javax.swing.JRadioButton C;
    private javax.swing.JRadioButton CK;
    private javax.swing.JRadioButton CKS;
    private javax.swing.ButtonGroup Jenis;
    private javax.swing.JTextField Nama;
    private javax.swing.JRadioButton S;
    private javax.swing.JComboBox<String> T;
    private javax.swing.JTextField Tm;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
