/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasilaundry;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import java.lang.String;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Mufidatun
 */
public class frmMain2 extends javax.swing.JFrame {

    /**
     * Creates new form frmMain2
     */
    public static String useraktif;
    public frmMain2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        Admin = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        Ts = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Harga = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Berat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Nama = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Tm = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        Jeniscuci = new javax.swing.JTextField();
        B1 = new javax.swing.JComboBox<>();
        T1 = new javax.swing.JComboBox<>();
        B2 = new javax.swing.JComboBox<>();
        T2 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        cek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(null);
        jPanel1.add(Admin);
        Admin.setBounds(110, 60, 77, 20);

        jButton2.setText("Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(130, 340, 77, 23);

        jLabel7.setText("Tanggal Selesai");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 270, 90, 14);

        Ts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TsActionPerformed(evt);
            }
        });
        jPanel1.add(Ts);
        Ts.setBounds(120, 260, 30, 30);

        jLabel8.setText("Harga");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(30, 310, 50, 14);
        jPanel1.add(Harga);
        Harga.setBounds(90, 300, 190, 30);

        jLabel4.setText("Berat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 150, 40, 14);

        jLabel6.setText("Tanggal Masuk");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 230, 93, 14);
        jPanel1.add(Berat);
        Berat.setBounds(90, 140, 140, 30);

        jLabel3.setText("Nama");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 100, 39, 14);
        jPanel1.add(Nama);
        Nama.setBounds(91, 96, 190, 30);

        jLabel5.setText("gram");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(240, 150, 37, 14);

        jLabel1.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 102));
        jLabel1.setText("Laundry Kita");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(90, 20, 199, 29);

        jLabel2.setText("Admin :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(56, 64, 53, 14);
        jPanel1.add(Tm);
        Tm.setBounds(120, 220, 30, 30);

        jLabel9.setText("Jenis");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 190, 50, 14);
        jPanel1.add(Jeniscuci);
        Jeniscuci.setBounds(90, 180, 190, 30);

        B1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(B1);
        B1.setBounds(160, 220, 40, 30);

        T1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022" }));
        jPanel1.add(T1);
        T1.setBounds(210, 220, 70, 30);

        B2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        jPanel1.add(B2);
        B2.setBounds(160, 260, 40, 30);

        T2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022" }));
        jPanel1.add(T2);
        T2.setBounds(210, 260, 70, 30);

        jButton3.setText("Save");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(210, 340, 80, 23);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, -4, 320, 380);

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Id_transaksi", "Nama", "Berat", "Tgl_masuk", "Tgl_selesai", "Bulan", "Tahun", "Jenis", "Harga", "Petugas"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel10.setFont(new java.awt.Font("Rockwell", 0, 24)); // NOI18N
        jLabel10.setText("Data Transaksi");

        jButton1.setText("Print");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        cek.setText("Cek");
        cek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(cek, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(172, 172, 172))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(cek))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(320, 0, 520, 380);

        setSize(new java.awt.Dimension(853, 416));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
         String halouser = Login.useraktif;
         String namapel = frmMain.nama;
         String beratbaju = frmMain.berat;
         String masuk = frmMain.Tglmasuk;
         String selesai = frmMain.Tglselesai;
         String harga2 = frmMain.harga;
         String Jenis = frmMain.jenis;
         String Bulan = frmMain.bulan;
         String Tahun = frmMain.tahun;
        
         
        Admin.setText(halouser);
        Nama.setText(namapel);
        Berat.setText(beratbaju);
        Tm.setText(masuk);
        Ts.setText(selesai);
        Jeniscuci.setText(Jenis);
        Harga.setText(harga2);
        B1.setSelectedItem(Bulan);
        B2.setSelectedItem(Bulan);
        T1.setSelectedItem(Tahun);
        T2.setSelectedItem(Tahun);
               
    }//GEN-LAST:event_formWindowOpened

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MessageFormat header = new MessageFormat("Rekap Data Laundry");
        MessageFormat footer = new MessageFormat("Page (0,number,integer)       ");
        try {
            jTable1.print(JTable.PrintMode.FIT_WIDTH, header, footer, true, null, true, null);
        } catch (java.awt.print.PrinterException e) {
            System.err.format("Cannot print %s%n", e.getMessage());
        } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void TsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TsActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
       String SQL = "INSERT INTO tb_tansaksi (Id_transaksi, Nama, Berat, Tgl_masuk, Tgl_selesai, Bulan, Tahun, Jenis, Harga, Petugas)"
                    + "VALUES(null,'" + Nama.getText() + "','" + Berat.getText() + "','" + Tm.getText() + "','" + Ts.getText() + "',"
                    + "'" + B1.getSelectedItem() + "','" + T1.getSelectedItem() + "','" + Jeniscuci.getText() + "','" + Harga.getText() + "','" + Admin.getText() + "')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Ditambahkan", "Sukses", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Data gagal ditambahkan", "Gagal", JOptionPane.WARNING_MESSAGE);
            } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_cekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmMain2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new frmMain2().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Admin;
    private javax.swing.JComboBox<String> B1;
    private javax.swing.JComboBox<String> B2;
    private javax.swing.JTextField Berat;
    private javax.swing.JTextField Harga;
    private javax.swing.JTextField Jeniscuci;
    private javax.swing.JTextField Nama;
    private javax.swing.JComboBox<String> T1;
    private javax.swing.JComboBox<String> T2;
    private javax.swing.JTextField Tm;
    private javax.swing.JTextField Ts;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cek;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        String kolom[] = {"Id_transaksi","Nama","Berat","Tgl_masuk","Tgl_selesai","Bulan","Tahun","Jenis","Harga","Petugas"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);
        String SQL = "SELECT * FROM tb_tansaksi";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
        
        try {
            while(rs.next()){
                String Id_transaksi = rs.getString(1);
                String Nama = rs.getString(2);
                String Berat = rs.getString(3);
                String Tgl_masuk = rs.getString(4);
                String Tgl_selesai = rs.getString(5);
                
                String Bulan = "";
                if ("1".equals(rs.getString(6))) {
                    Bulan = "1";
                } else if ("2".equals(rs.getString(6))) {
                    Bulan = "2";
                } else if ("3".equals(rs.getString(6))) {
                    Bulan = "3";
                } else if ("4".equals(rs.getString(6))) {
                    Bulan = "4";
                } else if ("5".equals(rs.getString(6))) {
                    Bulan = "5";
                } else if ("6".equals(rs.getString(6))) {
                    Bulan = "6";
                } else if ("7".equals(rs.getString(6))) {
                    Bulan = "7";
                } else if ("8".equals(rs.getString(6))) {
                    Bulan = "8";
                } else if ("9".equals(rs.getString(6))) {
                    Bulan = "9";
                } else if ("10".equals(rs.getString(6))) {
                    Bulan = "10";
                } else if ("11".equals(rs.getString(6))) {
                    Bulan = "11";
                } else {
                    Bulan = "12";
                }
                
                String Tahun = "";
                if ("2017".equals(rs.getString(7))) {
                    Tahun = "2017";
                } else if ("2018".equals(rs.getString(7))) {
                    Tahun = "2018";
                } else if ("2019".equals(rs.getString(7))) {
                    Tahun = "2019";
                } else if ("2020".equals(rs.getString(7))) {
                    Tahun = "2020";
                } else if ("2021".equals(rs.getString(7))) {
                    Tahun = "2021";
                } else  {
                    Tahun = "2022";
                }
                
                String Jenis = rs.getString(8);       
                String Harga = rs.getString(9);
                String Petugas = rs.getString(10);
    
                String data[] = {Id_transaksi,Nama,Berat,Tgl_masuk,Tgl_selesai,Bulan,Tahun,Jenis,Harga,Petugas};
                dtm.addRow(data);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmMain2.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTable1.setModel(dtm);
    }
}
