/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package aplikasilaundry;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hyung
 */
public class ManageAccount extends javax.swing.JFrame {

    /**
     * Creates new form ManageAccount
     */
    public ManageAccount() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        accmanagement = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        delacc = new javax.swing.JButton();
        addacc = new javax.swing.JButton();
        checkacc = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        usradmn = new javax.swing.JTextField();
        pswadmn = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        accmanagement.setBackground(new java.awt.Color(255, 204, 255));
        accmanagement.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Username", "Password"
            }
        ));
        accmanagement.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                accmanagementMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(accmanagement);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(0, 60, 260, 250);

        jPanel1.setBackground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Aller", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("ADMIN PAGE");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(70, 20, 120, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 260, 60);

        jPanel3.setBackground(new java.awt.Color(255, 0, 153));
        jPanel3.setLayout(null);

        delacc.setBackground(new java.awt.Color(255, 0, 0));
        delacc.setFont(new java.awt.Font("Aller", 1, 11)); // NOI18N
        delacc.setText("Delete");
        delacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delaccActionPerformed(evt);
            }
        });
        jPanel3.add(delacc);
        delacc.setBounds(20, 10, 70, 20);

        addacc.setBackground(new java.awt.Color(255, 0, 0));
        addacc.setFont(new java.awt.Font("Aller", 1, 11)); // NOI18N
        addacc.setText("Add");
        addacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addaccActionPerformed(evt);
            }
        });
        jPanel3.add(addacc);
        addacc.setBounds(170, 10, 70, 20);

        checkacc.setBackground(new java.awt.Color(0, 0, 255));
        checkacc.setFont(new java.awt.Font("Freshman", 0, 12)); // NOI18N
        checkacc.setText("Check");
        checkacc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkaccActionPerformed(evt);
            }
        });
        jPanel3.add(checkacc);
        checkacc.setBounds(90, 10, 80, 20);

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 310, 260, 40);

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setLayout(null);
        jPanel2.add(usradmn);
        usradmn.setBounds(10, 30, 170, 30);
        jPanel2.add(pswadmn);
        pswadmn.setBounds(10, 90, 170, 30);

        jLabel2.setText("Insert Password");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 70, 90, 20);

        jLabel5.setText("Insert Username");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(10, 10, 100, 20);

        jButton1.setText("Log in Form");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(10, 300, 170, 23);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(260, 0, 190, 350);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 250, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 60, 260, 250);

        setSize(new java.awt.Dimension(466, 389));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void delaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delaccActionPerformed
        // TODO add your handling code here:
        int baris = accmanagement.getSelectedRow();
        if (baris != -1) {
            String username = accmanagement.getValueAt(baris, 0).toString();
            String password = accmanagement.getValueAt(baris, 1).toString();
            String SQL = "DELETE FROM tb_akun WHERE username='"+username+"' AND password='"+password+"'";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Account deleted","STATUS", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Unable to delete the account","WARNING", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Account is not selected yet!", "WARNING", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_delaccActionPerformed

    private void checkaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkaccActionPerformed
        // TODO add your handling code here:
        selectData();
    }//GEN-LAST:event_checkaccActionPerformed

    private void addaccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addaccActionPerformed
        // TODO add your handling code here:
                if ("".equals(usradmn.getText()) || "".equals(pswadmn.getText())) {
            JOptionPane.showMessageDialog(this, "You cannot add a blank username & password!", "WARNING", JOptionPane.WARNING_MESSAGE);
        } else {
            String SQL = "INSERT INTO tb_akun (username, password) "
            + "VALUES('"+usradmn.getText()+"','"+pswadmn.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status == 1) {
                JOptionPane.showMessageDialog(this, "Username & Password added!", "CAUTION", JOptionPane.INFORMATION_MESSAGE);
                selectData();
            } else {
                JOptionPane.showMessageDialog(this, "Username & Password cannot be added!", "WARNING", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_addaccActionPerformed

    private void accmanagementMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_accmanagementMouseClicked
        // TODO add your handling code here:
        int baris = accmanagement.getSelectedRow();
        if (baris != -1) {
        }
    }//GEN-LAST:event_accmanagementMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        new Login().show();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed
public void selectData() {
    String kolom[] = {"username","password"};
            DefaultTableModel dtm = new DefaultTableModel(null, kolom);
            String SQL = "SELECT * FROM tb_akun";
            ResultSet rs = KoneksiDB.executeQuery(SQL);
            try {
                while (rs.next()) {
                    String username = rs.getString(1);
                    String password = rs.getString(2);
                    String data[] = {username, password};
                    dtm.addRow(data);
                }
            } catch (SQLException ex) {
                Logger.getLogger(frmMain.class.getName()).log(Level.SEVERE, null, ex);
            }
            accmanagement.setModel(dtm);
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable accmanagement;
    private javax.swing.JButton addacc;
    private javax.swing.JButton checkacc;
    private javax.swing.JButton delacc;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pswadmn;
    private javax.swing.JTextField usradmn;
    // End of variables declaration//GEN-END:variables
}
